---
- name: Ensure that AWS infrastructure are configured
  hosts: localhost
  tasks:
  - name: Wait for SSH to come up
    wait_for: host={{ item }} port=22 delay=60 timeout=320 state=started
    with_items: "{{ groups.all }}"

  - name: Add nodes to known hosts
    shell: ssh-keyscan -H {{ item }} >> ~/.ssh/known_hosts
    with_items: "{{ groups.all }}"